apiVersion: v1
kind: Service
metadata:
  name: arcade-loadbalancer
  namespace: arcade
spec:
  type: LoadBalancer
  selector:
    app: servidor-web            
  ports:
    - name: servidor-web
      port: 3000             
      targetPort: 3000     
