apiVersion: v1
kind: Service
metadata:
  name: servidor-web
  namespace: arcade
  labels:
    backstage.io/kubernetes-id: as-proyecto
spec:
  selector:
    app: servidor-web
    backstage.io/kubernetes-id: as-proyecto
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP