apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: arcade
  labels:
    backstage.io/kubernetes-id: as-proyecto
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: "jqX7#GvW4u!p9zK2@R8dL3^fZ0"
  APP_USER: Andoni
  APP_PWD: "Tm6%qD1!Zr8@vC4^xN7#hM2&yP9"
