apiVersion: apps/v1
kind: Deployment
metadata:
  name: juego-2048
  namespace: arcade
  labels:
    backstage.io/kubernetes-id: as-proyecto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juego-2048
      backstage.io/kubernetes-id: as-proyecto
  template:
    metadata:
      labels:
        app: juego-2048
        backstage.io/kubernetes-id: as-proyecto
    spec:
      containers:
        - name: juego-2048
          image: andonigarcia/arcade-2048:1.0.0
          ports:
            - containerPort: 80