apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
  namespace: arcade
  labels:
    backstage.io/kubernetes-id: as-proyecto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris
      backstage.io/kubernetes-id: as-proyecto
  template:
    metadata:
      labels:
        app: tetris
        backstage.io/kubernetes-id: as-proyecto
    spec:
      containers:
        - name: tetris
          image: andonigarcia/arcade-tetris:1.0.0
          ports:
            - containerPort: 80