apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arcade-paths
  namespace: arcade
spec:
  ingressClassName: nginx
  rules:
    - host: arcade
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: servidor-web
                port:
                  number: 3000
          - path: /db
            pathType: Prefix
            backend:
              service: 
                name: servidor-bbdd
                port:
                  number: 27017
          - path: /pacman
            pathType: Prefix
            backend:
              service:
                name: pacman
                port:
                  number: 80
          - path: /2048
            pathType: Prefix
            backend:
              service:
                name: juego-2048
                port:
                  number: 80
          - path: /tetris
            pathType: Prefix
            backend:
              service:
                name: tetris
                port:
                  number: 80